#### Cleaning Data

In [1]:
import  pandas as pd
import numpy as np
data = {
    'Name': ['Alice',' Bob', 'Charlie', 'Mike', 'Dave', 'Monica', 'Esther', 'Paul', 'Vic' ],
    'Age': [20, None, 89, 56, None, 46, 18, 88, 77],
    'City': ['Nairobi', 'NY', 'MSA', 'LA', None, 'Nakuru', 'Eldoret', None, 'Kampala'],
    'Team':['Arsenal', 'Real Madrid', None, 'Manchester', 'PSG', 'Liverpool', 'Juventus', 'Barcelona', None]
}
 
df = pd.DataFrame(data)

In [2]:
df.head()

      Name   Age     City         Team
0    Alice  20.0  Nairobi      Arsenal
1      Bob   NaN       NY  Real Madrid
2  Charlie  89.0      MSA          NaN
3     Mike  56.0       LA   Manchester
4     Dave   NaN      NaN          PSG

In [3]:
df

      Name   Age     City         Team
0    Alice  20.0  Nairobi      Arsenal
1      Bob   NaN       NY  Real Madrid
2  Charlie  89.0      MSA          NaN
3     Mike  56.0       LA   Manchester
4     Dave   NaN      NaN          PSG
5   Monica  46.0   Nakuru    Liverpool
6   Esther  18.0  Eldoret     Juventus
7     Paul  88.0      NaN    Barcelona
8      Vic  77.0  Kampala          NaN

In [4]:
df.isna().sum()

Name    0
Age     2
City    2
Team    2
dtype: int64

In [5]:
df.isnull()

    Name    Age   City   Team
0  False  False  False  False
1  False   True  False  False
2  False  False  False   True
3  False  False  False  False
4  False   True   True  False
5  False  False  False  False
6  False  False  False  False
7  False  False   True  False
8  False  False  False   True

In [6]:
df.isnull().sum()

Name    0
Age     2
City    2
Team    2
dtype: int64

In [7]:
#removing missing values
df_clean = df.dropna()
df_clean

     Name   Age     City        Team
0   Alice  20.0  Nairobi     Arsenal
3    Mike  56.0       LA  Manchester
5  Monica  46.0   Nakuru   Liverpool
6  Esther  18.0  Eldoret    Juventus

In [8]:
#filling missing values with a specific value
df_filled = df.fillna('Unknown')
df_filled

      Name      Age     City         Team
0    Alice     20.0  Nairobi      Arsenal
1      Bob  Unknown       NY  Real Madrid
2  Charlie     89.0      MSA      Unknown
3     Mike     56.0       LA   Manchester
4     Dave  Unknown  Unknown          PSG
5   Monica     46.0   Nakuru    Liverpool
6   Esther     18.0  Eldoret     Juventus
7     Paul     88.0  Unknown    Barcelona
8      Vic     77.0  Kampala      Unknown

In [9]:
#filling the NaN using a fill
df_ffil= df.ffill()
df_ffil

      Name   Age     City         Team
0    Alice  20.0  Nairobi      Arsenal
1      Bob  20.0       NY  Real Madrid
2  Charlie  89.0      MSA  Real Madrid
3     Mike  56.0       LA   Manchester
4     Dave  56.0       LA          PSG
5   Monica  46.0   Nakuru    Liverpool
6   Esther  18.0  Eldoret     Juventus
7     Paul  88.0  Eldoret    Barcelona
8      Vic  77.0  Kampala    Barcelona

In [10]:
# Create extended sample dataframe
import pandas as pd
import numpy as np
 
data2 = {
    'full_name': [
        'Alice', 'Bob', 'Charlie', 'Mike', 'Dave',
        'Monica', 'Esther', 'Brian', 'Linda', 'James',
        'Kevin', 'Lucy', 'Daniel', 'Grace', 'Peter'
    ],
    'age_years': [
        20, None, 89, 29, None,
        45, 18, 34, None, 41,
        25, None, 52, 33, None
    ],
    'home_county': [
        'Nairobi', 'Kajiado', 'Rongai', None, 'Kisumu',
        None, 'Lamu', 'Nakuru', 'Mombasa', None,
        'Eldoret', 'Kisii', None, 'Nyeri', 'Machakos'
    ],
    'favorite_club': [
        'Arsenal', 'Real Madrid', 'Chelsea', 'Manchester United', None,
        'PSG', None, 'Manchester City', 'Barcelona', 'Liverpool',
        None, 'Tottenham', 'Juventus', None, 'AC Milan'
    ],
    # Extra Column 1 (with missing values)
    'salary_kes': [
        50000, None, 120000, 75000, None,
        68000, 45000, None, 98000, 105000,
        None, 72000, 130000, None, 88000
    ],
    # Extra Column 2 (with missing values)
    'years_experience': [
        2, 5, None, 4, None,
        8, 1, None, 6, 10,
        None, 3, 12, None, 7
    ],
    # Extra Column 3 (with missing values)
    'performance_score': [
        78, None, 92, 85, None,
        88, 70, None, 90, 95,
        None, 80, 93, None, 87
    ]
}
 
df1 = pd.DataFrame(data2)
 
df1.head()

,full_name,age_years,home_county,favorite_club,salary_kes,years_experience,performance_score
0,Alice,20.0,Nairobi,Arsenal,50000.0,2.0,78.0
1,Bob,NaN,Kajiado,Real Madrid,NaN,5.0,NaN
2,Charlie,89.0,Rongai,Chelsea,120000.0,NaN,92.0
3,Mike,29.0,NaN,Manchester United,75000.0,4.0,85.0
4,Dave,NaN,Kisumu,NaN,NaN,NaN,NaN

In [11]:
# ### Question:

# 1. Fill the NaN in the data using best apprwach p
# 2. Convert the columns into its correct data type
# 3. Rename the columns into the best namings possible

df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   full_name          15 non-null     str
 1   age_years          10 non-null     float64
 2   home_county        11 non-null     str
 3   favorite_club      11 non-null     str
 4   salary_kes         10 non-null     float64
 5   years_experience   10 non-null     float64
 6   performance_score  10 non-null     float64
dtypes: float64(4), str(3)
memory usage: 972.0 bytes

In [12]:
student_data = {

    'firstname': ['Alice', 'Bob', 'Charlie', 'Eve', 'David', 'Charlie', 'Frank', 'Bob', 'Grace', 'Eve'],

    'lastname': ['Smith', 'Johnson', 'Brown', 'Davis', 'Williams', 'Brown', 'Miller', 'Johnson', 'Wilson', 'Davis'],

    'subject': ['Math', 'Science', 'History', 'Physics', 'English', 'History', 'Chemistry', 'Science', 'Biology', 'Physics'],

    'adm_year': [2023, 2022, 2024, 2022, 2023, 2024, 2024, 2022, 2023, 2022],  

    'lecturer': ['Dr. A', 'Dr. B', 'Dr. C', 'Dr. E', 'Dr. D', 'Dr. C', 'Dr. F', 'Dr. B', 'Dr. G', 'Dr. E']

}
 
df2 = pd.DataFrame(student_data)

df2

  firstname  lastname    subject  adm_year lecturer
0     Alice     Smith       Math      2023    Dr. A
1       Bob   Johnson    Science      2022    Dr. B
2   Charlie     Brown    History      2024    Dr. C
3       Eve     Davis    Physics      2022    Dr. E
4     David  Williams    English      2023    Dr. D
5   Charlie     Brown    History      2024    Dr. C
6     Frank    Miller  Chemistry      2024    Dr. F
7       Bob   Johnson    Science      2022    Dr. B
8     Grace    Wilson    Biology      2023    Dr. G
9       Eve     Davis    Physics      2022    Dr. E

#### Identifying Duplicates

In [14]:
df2.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
6    False
7     True
8    False
9     True
dtype: bool

In [16]:
df2.duplicated().sum()

np.int64(3)

In [26]:
df2 = df2.drop_duplicates()
df2_unique

  firstname  lastname    subject  adm_year lecturer
0     Alice     Smith       Math      2023    Dr. A
1       Bob   Johnson    Science      2022    Dr. B
2   Charlie     Brown    History      2024    Dr. C
3       Eve     Davis    Physics      2022    Dr. E
4     David  Williams    English      2023    Dr. D
6     Frank    Miller  Chemistry      2024    Dr. F
8     Grace    Wilson    Biology      2023    Dr. G

In [27]:
df2_unique.duplicated()

0    False
1    False
2    False
3    False
4    False
6    False
8    False
dtype: bool

In [19]:
df2_unique_cols = df2_unique.drop_duplicates(subset=['firstname', 'lastname'])
df2_unique_cols

  firstname  lastname    subject  adm_year lecturer
0     Alice     Smith       Math      2023    Dr. A
1       Bob   Johnson    Science      2022    Dr. B
2   Charlie     Brown    History      2024    Dr. C
3       Eve     Davis    Physics      2022    Dr. E
4     David  Williams    English      2023    Dr. D
6     Frank    Miller  Chemistry      2024    Dr. F
8     Grace    Wilson    Biology      2023    Dr. G

#### Conversion From Capital to Small and vice cersa

In [20]:
type(df2_unique_cols)

pandas.DataFrame

In [28]:
df2.info()

<class 'pandas.DataFrame'>
Index: 7 entries, 0 to 8
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   firstname  7 non-null      str
 1   lastname   7 non-null      str
 2   subject    7 non-null      str
 3   adm_year   7 non-null      int64
 4   lecturer   7 non-null      str
dtypes: int64(1), str(4)
memory usage: 336.0 bytes

In [29]:
df2['firstname'] = df2['firstname'].str.upper()
df2

  firstname  lastname    subject  adm_year lecturer
0     ALICE     Smith       Math      2023    Dr. A
1       BOB   Johnson    Science      2022    Dr. B
2   CHARLIE     Brown    History      2024    Dr. C
3       EVE     Davis    Physics      2022    Dr. E
4     DAVID  Williams    English      2023    Dr. D
6     FRANK    Miller  Chemistry      2024    Dr. F
8     GRACE    Wilson    Biology      2023    Dr. G

In [37]:
import pandas as pd

call_df = pd.read_excel('customer_call_list.xlsx')
call_df.head()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True

In [38]:
call_df.dtypes

CustomerID            int64
First_Name              str
Last_Name               str
Phone_Number         object
Address                 str
Paying Customer         str
Do_Not_Contact          str
Not_Useful_Column      bool
dtype: object

In [40]:
call_df.isnull().sum()

CustomerID           0
First_Name           0
Last_Name            1
Phone_Number         2
Address              0
Paying Customer      0
Do_Not_Contact       4
Not_Useful_Column    0
dtype: int64

In [43]:
call_df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20     True
dtype: bool

In [48]:
call_df_clean = call_df.drop_duplicates( subset = ['CustomerID'])
call_df_clean

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [47]:
# delete the useless column

call_df_clean = call_df_clean.drop(columns=['Not_Useful_Column'])
call_df_clean()

KeyError: "['Not_Useful_Column'] not found in axis"