In [1]:
import pandas as pd

data = {'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}
series = pd.Series(data)
print(series)

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [6]:
#accessing elements in the series
print("Element at index 'c':", series['c'])

# accessing 3 elements starting from index 'b'
print("Elements from index 'b' to 'd':\n", series['b':'d'])

Element at index 'c': 30
Elements from index 'b' to 'd':
 b    20
c    30
d    40
dtype: int64

#### Creating a Dataframe from Lists

In [7]:
lst = [1, 2, 3, 4, 5]
type(lst)
print   ("Type of lst:", type(lst))

Type of lst: <class 'list'>

In [8]:
lst_df = pd.DataFrame(lst, columns=['Years'])
lst_df

   Years
0      1
1      2
2      3
3      4
4      5

In [12]:
cars_rating = [
    ["Toyota", 8.5],
    ["VW", 9.0],
    ["Ford", 7.5],
    ["BMW", 8.0],
    ["Audi", 8.8]
]
cars_rating

[['Toyota', 8.5], ['VW', 9.0], ['Ford', 7.5], ['BMW', 8.0], ['Audi', 8.8]]

In [13]:
rating_df = pd.DataFrame(cars_rating, columns=['Car Brand', 'Rating'])
rating_df

  Car Brand  Rating
0    Toyota     8.5
1        VW     9.0
2      Ford     7.5
3       BMW     8.0
4      Audi     8.8

In [14]:
rating_df = pd.DataFrame(cars_rating)
rating_df

        0    1
0  Toyota  8.5
1      VW  9.0
2    Ford  7.5
3     BMW  8.0
4    Audi  8.8

In [ ]:
# Qn.Create a List of Lists shoppoing inventory

# 5 rows 4 columns and Name them accordingly
shopping_inventory = [
    ["Apples", 50, 30, "Fruits"],
    ["Bananas", 30, 10, "Fruits"],
    ["Carrots", 20, 80, "Vegetables"],
    ["Detergent", 15, 500, "Household"],
    ["Eggs", 60, 450, "Dairy"]
]
inventory_df = pd.DataFrame(shopping_inventory, columns=['Item', 'Quantity', 'Price', 'Category'])
inventory_df

        Item  Quantity  Price    Category
0     Apples        50     30      Fruits
1    Bananas        30     10      Fruits
2    Carrots        20     80  Vegetables
3  Detergent        15    500   Household
4       Eggs        60    450       Dairy

In [17]:
# Question: Create 4 separate lists of your own for a meeting. Then combine them into a dictionary. Then convert into a pandas df.

attendees = ["Alice", "Bob", "Charlie", "David"]
times = ["10:00 AM", "10:15 AM", "10:30 AM", "10:45 AM"]
dates = ["2026-07-02", "2026-09-02", "2026-06-02", "2026-07-02"]
locations = ["Room 101", "Room 102", "Room 103", "Room 104"]


meeting_dict = {
    'Attendee': attendees,  
    'Time': times,
    'Date': dates,  
    'Location': locations
}
meeting_df = pd.DataFrame(meeting_dict)
meeting_df

  Attendee      Time        Date  Location
0    Alice  10:00 AM  2026-07-02  Room 101
1      Bob  10:15 AM  2026-09-02  Room 102
2  Charlie  10:30 AM  2026-06-02  Room 103
3    David  10:45 AM  2026-07-02  Room 104

In [18]:
std_df2 = pd.DataFrame(meeting_dict, index=['A', 'B', 'C', 'D'])
std_df2

  Attendee      Time        Date  Location
A    Alice  10:00 AM  2026-07-02  Room 101
B      Bob  10:15 AM  2026-09-02  Room 102
C  Charlie  10:30 AM  2026-06-02  Room 103
D    David  10:45 AM  2026-07-02  Room 104

#### Creating a df from a list of Dictionaries

In [20]:
# creating a list of dictionaries where each dictionary represents a row of data using the premier league teams
premier_league_teams = [
    {"Team": "Manchester United", "Points": 55, "Position": 3},
    {"Team": "Liverpool", "Points": 80, "Position": 1},
    {"Team": "Chelsea", "Points": 75, "Position": 2},
    {"Team": "Arsenal", "Points": 60, "Position": 4},
    {"Team": "Manchester City", "Points": 70, "Position": 5}
]
premier_league_df = pd.DataFrame(premier_league_teams)
premier_league_df
#sort by points
premier_league_df.sort_values(by='Points', ascending=False)

                Team  Points  Position
1          Liverpool      80         1
2            Chelsea      75         2
4    Manchester City      70         5
3            Arsenal      60         4
0  Manchester United      55         3

In [9]:
#Importing data from    a CSV file into a pandas DataFrame and displaying the first few rows of the DataFrame.
csv_file_path = 'netflix_csv.csv' 
netflix_df = pd.read_csv(csv_file_path)
print(netflix_df.head())

AttributeError: 'DataFrame' object has no attribute 'read_csv'

In [3]:
#printing the column names of the DataFrame to understand the structure of the data.
print(netflix_df.columns)

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='str')

In [8]:

df= pd.DataFrame(netflix_df)
df.head()

AttributeError: 'DataFrame' object has no attribute 'DataFrame'

In [5]:
#checking null values in the DataFrame
print(netflix_df.isnull().sum())

show_id            0
type               0
title              0
director        1969
cast             570
country          476
date_added        11
release_year       0
rating            10
duration           0
listed_in          0
description        0
dtype: int64

In [6]:
pd.isna()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,True,False,False,False,False,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False
3,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
6229,False,False,False,True,False,False,True,False,False,False,False,False
6230,False,False,False,True,False,False,True,False,False,False,False,False
6231,False,False,False,True,True,True,True,False,True,False,False,False
6232,False,False,False,True,False,False,True,False,False,False,False,False
6233,False,False,False,True,False,False,True,False,False,False,False,False